import type { Pizza } from '@@/types/Pizza';

export const pizzas: Pizza[] = [
  {
    id: 1,
    name: 'Маргарита',
    image: '1.jpg',
    ingridients: [1, 2, 25],
    rating: 5,
    variants: [
      { dough: 1, size: 'sm', price: 400 },
      { dough: 1, size: 'md', price: 500 },
      { dough: 1, size: 'lg', price: 600 },
      { dough: 2, size: 'sm', price: 450 },
      { dough: 2, size: 'md', price: 550 },
      { dough: 2, size: 'lg', price: 650 },
    ],
    avalible_topings: [1, 2, 3],
  },
  {
    id: 2,
    name: 'Грибная',
    image: '2.jpg',
    ingridients: [1, 5, 10],
    rating: 4.8,
    variants: [
      { dough: 1, size: 'sm', price: 420 },
      { dough: 1, size: 'md', price: 520 },
      { dough: 1, size: 'lg', price: 620 },
      { dough: 2, size: 'sm', price: 470 },
      { dough: 2, size: 'md', price: 570 },
      { dough: 2, size: 'lg', price: 670 },
    ],
    avalible_topings: [7, 9, 10],
  },
  {
    id: 3,
    name: 'Пепперони',
    image: '3.jpg',
    ingridients: [2, 3, 7],
    rating: 4.9,
    variants: [
      { dough: 1, size: 'sm', price: 420 },
      { dough: 1, size: 'md', price: 520 },
      { dough: 1, size: 'lg', price: 620 },
      { dough: 2, size: 'sm', price: 470 },
      { dough: 2, size: 'md', price: 570 },
      { dough: 2, size: 'lg', price: 670 },
    ],
    avalible_topings: [5],
  },
  {
    id: 4,
    name: 'С беконом',
    image: '4.jpg',
    ingridients: [1, 3, 14, 10],
    rating: 4.1,
    variants: [
      { dough: 1, size: 'sm', price: 420 },
      { dough: 1, size: 'md', price: 520 },
      { dough: 1, size: 'lg', price: 620 },
      { dough: 2, size: 'sm', price: 470 },
      { dough: 2, size: 'md', price: 570 },
      { dough: 2, size: 'lg', price: 670 },
    ],
    avalible_topings: [7, 8, 9, 10],
  },
  {
    id: 5,
    name: 'Гавайская',
    image: '5.jpg',
    ingridients: [6, 15],
    rating: 3.2,
    variants: [
      { dough: 1, size: 'sm', price: 320 },
      { dough: 1, size: 'md', price: 380 },
      { dough: 1, size: 'lg', price: 430 },
      { dough: 2, size: 'sm', price: 370 },
      { dough: 2, size: 'md', price: 400 },
      { dough: 2, size: 'lg', price: 420 },
    ],
    avalible_topings: [3, 8, 12],
  },
  {
    id: 6,
    name: 'Морская',
    image: '6.jpg',
    ingridients: [1, 2, 12, 10],
    rating: 3.9,
    variants: [
      { dough: 1, size: 'sm', price: 590 },
      { dough: 1, size: 'md', price: 600 },
      { dough: 1, size: 'lg', price: 620 },
      { dough: 2, size: 'sm', price: 615 },
      { dough: 2, size: 'md', price: 640 },
      { dough: 2, size: 'lg', price: 699 },
    ],
    avalible_topings: [2, 3, 6],
  },
  {
    id: 7,
    name: 'Веганская',
    image: '7.jpg',
    ingridients: [1, 4, 12, 10, 8, 16],
    rating: 2.1,
    variants: [
      { dough: 1, size: 'sm', price: 590 },
      { dough: 1, size: 'md', price: 600 },
      { dough: 1, size: 'lg', price: 620 },
      { dough: 2, size: 'sm', price: 615 },
      { dough: 2, size: 'md', price: 640 },
      { dough: 2, size: 'lg', price: 699 },
    ],
    avalible_topings: [1, 2, 5],
  },
  {
    id: 8,
    name: 'Овощная',
    image: '8.jpg',
    ingridients: [1, 2, 8, 10, 12],
    rating: 4.3,
    variants: [
      { dough: 1, size: 'sm', price: 590 },
      { dough: 1, size: 'md', price: 600 },
      { dough: 1, size: 'lg', price: 620 },
      { dough: 2, size: 'sm', price: 615 },
      { dough: 2, size: 'md', price: 640 },
      { dough: 2, size: 'lg', price: 699 },
    ],
    avalible_topings: [6, 11, 12],
  },
  {
    id: 9,
    name: 'Острая',
    image: '9.jpg',
    ingridients: [7, 8, 11],
    rating: 5,
    variants: [
      { dough: 1, size: 'sm', price: 590 },
      { dough: 1, size: 'md', price: 600 },
      { dough: 1, size: 'lg', price: 620 },
      { dough: 2, size: 'sm', price: 615 },
      { dough: 2, size: 'md', price: 640 },
      { dough: 2, size: 'lg', price: 699 },
    ],
    avalible_topings: [],
  },
];
